# Generated by Django 4.0.5 on 2022-10-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='email',
            field=models.EmailField(max_length=230),
        ),
        migrations.AlterField(
            model_name='demo',
            name='mobile',
            field=models.CharField(max_length=220),
        ),
    ]
